---
- name: Get CPU Utilization  # noqa no-changed-when
  ansible.builtin.shell: sudo systemctl status firewalld > /tmp/service.txt

- name: Update an incident in ServiceNow
  servicenow.itsm.incident:
    instance:
      host: "{{ lookup('env', 'SN_HOST') }}"
      password: "{{ lookup('env', 'SN_PASSWORD') }}"
      username: "{{ lookup('env', 'SN_USERNAME') }}"
    state: in_progress
    number: "{{ req_number }}"
    urgency: "{{ ansible_eda.event.urgency }}"
    impact: "{{ ansible_eda.event.impact }}"
    other:
      comments: "This is automated enrichment of ServiceNow tickets with EDA."
    attachments:
      - path: /tmp/service.txt
        name: "Firewalld Status"
