---
- name: Check firewalld status (non-failing)
  ansible.builtin.command: systemctl status firewalld
  register: firewalld_status
  changed_when: false
  failed_when: firewalld_status.rc not in [0, 3]
  become: true

- name: Write firewalld status to file
  ansible.builtin.copy:
    dest: /tmp/service.txt
    content: "{{ (firewalld_status.stdout | default('')).strip() if firewalld_status.rc == 0 else 'inactive' }}"
  become: true
  
- name: Update an incident in ServiceNow
  servicenow.itsm.incident:
    instance:
      host: "{{ lookup('env', 'SN_HOST') }}"
      password: "{{ lookup('env', 'SN_PASSWORD') }}"
      username: "{{ lookup('env', 'SN_USERNAME') }}"
    state: in_progress
    number: "{{ req_number }}"
    urgency: "{{ ansible_eda.event.urgency }}"
    impact: "{{ ansible_eda.event.impact }}"
    other:
      comments: "This is automated enrichment of ServiceNow tickets with EDA."
    attachments:
      - path: /tmp/service.txt
        name: "Firewalld Status"
