---
- name: Get Firewalld Status  # noqa no-changed-when
  ansible.builtin.shell: systemctl status firewalld > /tmp/service.txt
  register: result
  changed_when: false
  failed_when: result.rc not in [0, 3]
  become: true
  
- name: Update an incident in ServiceNow
  servicenow.itsm.incident:
    instance:
      host: "{{ lookup('env', 'SN_HOST') }}"
      password: "{{ lookup('env', 'SN_PASSWORD') }}"
      username: "{{ lookup('env', 'SN_USERNAME') }}"
    state: in_progress
    number: "{{ req_number }}"
    urgency: "{{ ansible_eda.event.urgency }}"
    impact: "{{ ansible_eda.event.impact }}"
    other:
      comments: "This is automated enrichment of ServiceNow tickets with EDA."
    attachments:
      - path: /tmp/service.txt
        name: "Firewalld Status"
