---
- name: ServiceNow Incident Monitor with Change Request Decision Engine
  hosts: all
  sources:
    - name: Monitor ServiceNow incidents for changes
      servicenow.itsm.records:
        table: incident
        interval: 10
        fields:
          - sys_id
          - number
          - short_description
          - description
          - priority
          - urgency
          - impact
          - state
          - category
          - subcategory
          - assignment_group
          - assigned_to
          - sys_created_on
          - sys_updated_on
          - sys_mod_count
          - sys_class_name
          - work_notes
          - comments
          - resolution_notes
          - close_code
          - close_notes
    
    - name: Monitor ServiceNow incidents for changes
      servicenow.itsm.records:
        table: change_request
        interval: 10

  rules:
    # Create change request for software incidents with patch keyword
    - name: Create change request for software incidents with patch keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count == "1" and (event.category == "Software" or event.category == "software") and event.short_description == "test patch deployment"
      action:
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring patch changes"

    # Create change request for software incidents with update keyword
    - name: Create change request for software incidents with update keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count == "1" and (event.category == "Software" or event.category == "software") and ("update" in event.short_description or "Update" in event.short_description or "UPDATE" in event.short_description)
      action:
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring update changes"

