---
- name: ServiceNow Incident Monitor with Change Request Decision Engine
  hosts: all
  sources:
    - name: Monitor ServiceNow incidents for changes
      servicenow.itsm.records:
        table: incident
        interval: 10
        fields:
          - sys_id
          - number
          - short_description
          - description
          - priority
          - urgency
          - impact
          - state
          - category
          - subcategory
          - assignment_group
          - assigned_to
          - sys_created_on
          - sys_updated_on
          - sys_mod_count
          - work_notes
          - comments
          - resolution_notes
          - close_code
          - close_notes

  rules:
    # Create change request for software incidents with specific keywords
    - name: Create change request for software incidents with specific keywords
      condition:
        all:
          - event.sys_class_name == "incident"
          - event.sys_mod_count == "0"
          - event.category == "Software"
          - any:
              - "patch" in event.short_description.lower()
              - "update" in event.short_description.lower()
              - "upgrade" in event.short_description.lower()
              - "deployment" in event.short_description.lower()
              - "configuration" in event.short_description.lower()
              - "database" in event.short_description.lower()
      action:
        debug:
          msg: "Software incident {{ event.number }} with change-related keywords requires change request"
        run_job_template:
          name: "Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring configuration or deployment changes"
