---
- name: ServiceNow Incident Monitor with Change Request Decision Engine
  hosts: all
  sources:
    - name: Monitor ServiceNow incidents for changes
      servicenow.itsm.records:
        table: incident
        interval: 10
        fields:
          - sys_id
          - number
          - short_description
          - description
          - priority
          - urgency
          - impact
          - state
          - category
          - subcategory
          - assignment_group
          - assigned_to
          - sys_created_on
          - sys_updated_on
          - sys_mod_count
          - sys_class_name
          - work_notes
          - comments
          - resolution_notes
          - close_code
          - close_notes

  rules:
    # Debug rule to see all event fields
    - name: Debug - Log all event fields
      condition: event.number is defined
      action:
        debug:
          msg: "Event received - Number: {{ event.number }}, Category: {{ event.category }}, sys_class_name: {{ event.sys_class_name | default('MISSING') }}, sys_mod_count: {{ event.sys_mod_count | default('MISSING') }}, short_description: {{ event.short_description | default('MISSING') }}"
    
    # Test rule for software category incidents (without missing fields)
    - name: Test - Software category incident detected
      condition: event.category == "software"
      action:
        debug:
          msg: "Software category incident detected: {{ event.number }} - This rule works!"
    
    # Create change request for software incidents with patch keyword
    - name: Create change request for software incidents with patch keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("patch" in event.short_description or "Patch" in event.short_description or "PATCH" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with patch keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring patch changes"

    # Create change request for software incidents with update keyword
    - name: Create change request for software incidents with update keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("update" in event.short_description or "Update" in event.short_description or "UPDATE" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with update keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring update changes"

    # Create change request for software incidents with upgrade keyword
    - name: Create change request for software incidents with upgrade keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("upgrade" in event.short_description or "Upgrade" in event.short_description or "UPGRADE" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with upgrade keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring upgrade changes"

    # Create change request for software incidents with deployment keyword
    - name: Create change request for software incidents with deployment keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("deployment" in event.short_description or "Deployment" in event.short_description or "DEPLOYMENT" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with deployment keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring deployment changes"

    # Create change request for software incidents with configuration keyword
    - name: Create change request for software incidents with configuration keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("configuration" in event.short_description or "Configuration" in event.short_description or "CONFIGURATION" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with configuration keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring configuration changes"

    # Create change request for software incidents with database keyword
    - name: Create change request for software incidents with database keyword
      condition: event.sys_class_name == "incident" and event.sys_mod_count >= "1" and (event.category == "Software" or event.category == "software") and ("database" in event.short_description or "Database" in event.short_description or "DATABASE" in event.short_description)
      action:
        debug:
          msg: "Software incident {{ event.number }} with database keyword requires change request"
        run_job_template:
          name: "SNOW: Create Software Change Request"
          organization: SNOW
          post_events: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.sys_id }}"
              incident_number: "{{ event.number }}"
              incident_category: "{{ event.category }}"
              change_type: "standard"
              change_reason: "Software incident requiring database changes"
