---
- name: Generic new poll for new records in ServiceNow and process the incidents. 
  hosts: all
  sources:
    - name: Watch for any updated incidents
      servicenow.itsm.records:
        table: incident
        interval: 5

  rules:
    - name: New record created and debug
      condition: event.sys_id is defined
      action:
        debug:

    - name: Enrich new REQ received from Service Catalog
      condition: event.sys_class_name == "sc_request" and event.sys_mod_count == "0"
      action:
        run_job_template:
          name: "EDA Enrich ServiceNow REQ"
          organization: Infrastructure
          post_events: true
          job_args:
            extra_vars:
              req_sys_id: "{{ event.sys_id }}"
              req_number: "{{ event.number }}"
