---
- name: Alert for Change Request Starting Soon
  hosts: localhost
  gather_facts: false
  vars:
    # Extract variables from the event data structure
    change_request_number: "{{ ansible_eda.event.change_request_number }}"
    change_request_sys_id: "{{ ansible_eda.event.change_request_sys_id }}"
    change_request_state: "{{ ansible_eda.event.change_request_state }}"
    planned_start_date: "{{ ansible_eda.event.planned_start_date }}"
    planned_end_date: "{{ ansible_eda.event.planned_end_date }}"
    assignment_group: "{{ ansible_eda.event.assignment_group }}"
    assigned_to: "{{ ansible_eda.event.assigned_to }}"
    short_description: "{{ ansible_eda.event.short_description }}"
    priority: "{{ ansible_eda.event.priority }}"
    urgency: "{{ ansible_eda.event.urgency }}"
    impact: "{{ ansible_eda.event.impact }}"
    alert_type: "{{ ansible_eda.event.alert_type }}"

  tasks:
    - name: Debug received start date alert data
      debug:
        msg: |
          Received ServiceNow change request start date alert data:
          - Change Request Number: {{ change_request_number }}
          - Change Request Sys ID: {{ change_request_sys_id }}
          - State: {{ change_request_state }}
          - Planned Start Date: {{ planned_start_date }}
          - Planned End Date: {{ planned_end_date }}
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}
          - Short Description: {{ short_description }}
          - Priority: {{ priority }}
          - Urgency: {{ urgency }}
          - Impact: {{ impact }}
          - Alert Type: {{ alert_type }}

    - name: Get change request details from ServiceNow
      servicenow.itsm.change_request_info:
        sys_id: "{{ change_request_sys_id }}"
      register: change_request_details

    - name: Calculate time until start date
      set_fact:
        current_time: "{{ ansible_date_time.epoch | int }}"
        start_time: "{{ planned_start_date | to_datetime('%Y-%m-%d %H:%M:%S') | int }}"
        time_until_start: "{{ (start_time - current_time) | int }}"
        hours_until_start: "{{ (time_until_start / 3600) | round(2) }}"
        minutes_until_start: "{{ (time_until_start / 60) | round(2) }}"

    - name: Debug time calculation
      debug:
        msg: |
          Start Date Alert Calculation:
          - Current Time: {{ current_time }}
          - Start Time: {{ start_time }}
          - Time Until Start: {{ time_until_start }} seconds
          - Hours Until Start: {{ hours_until_start }}
          - Minutes Until Start: {{ minutes_until_start }}

    - name: Update change request with start date alert
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_sys_id }}"
        work_notes: |
          ⏰ START DATE ALERT ⏰
          
          Change Request Starting Soon:
          - Planned Start Date: {{ planned_start_date }}
          - Time Until Start: {{ hours_until_start }} hours ({{ minutes_until_start }} minutes)
          - Alert Type: {{ alert_type }}
          - Alert Time: {{ ansible_date_time.iso8601 }}
          
          Change Request Details:
          - Number: {{ change_request_number }}
          - State: {{ change_request_state }}
          - Short Description: {{ short_description }}
          - Priority: {{ priority }}
          - Urgency: {{ urgency }}
          - Impact: {{ impact }}
          - Planned End Date: {{ planned_end_date }}
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}
          
          Please ensure all preparations are complete and the implementation team is ready to begin work.
          
          Alert generated by Event-Driven Ansible.
      register: change_request_alert_result

    - name: Debug alert result
      debug:
        msg: |
          Change Request Start Date Alert Updated:
          - Change Request Number: {{ change_request_alert_result.record.number }}
          - Hours Until Start: {{ hours_until_start }}
          - Minutes Until Start: {{ minutes_until_start }}
          - Work Notes Updated: Yes
          - Alert Time: {{ ansible_date_time.iso8601 }}

    - name: Set fact for alert processing
      set_fact:
        change_request_alerted: true
        change_request_number: "{{ change_request_number }}"
        change_request_sys_id: "{{ change_request_sys_id }}"
        hours_until_start: "{{ hours_until_start }}"
        minutes_until_start: "{{ minutes_until_start }}"
        alert_time: "{{ ansible_date_time.iso8601 }}"

    - name: Display alert success message
      debug:
        msg: |
          Change Request Start Date Alert Sent Successfully!

          Change Request Details:
          - Number: {{ change_request_number }}
          - Sys ID: {{ change_request_sys_id }}
          - State: {{ change_request_state }}
          - Planned Start Date: {{ planned_start_date }}
          - Time Until Start: {{ hours_until_start }} hours ({{ minutes_until_start }} minutes)
          - Priority: {{ priority }}
          - Urgency: {{ urgency }}
          - Impact: {{ impact }}
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}
          - Alert Type: {{ alert_type }}

          Stakeholders have been alerted that this change request is starting soon.
