---
- name: Close out the CR and Incident 
  hosts: localhost
  gather_facts: false
  tasks:    
    - name: Build closing notes
      ansible.builtin.set_fact:
        closing_notes: |
          EDA implementation completed. Closing change request.
          Short Description: {{ short_description }}
          Priority/Urgency/Impact: {{ priority }}/{{ urgency }}/{{ impact }}
          Assignment: {{ assignment_group }} / {{ assigned_to }}
          EDA-CLOSURE-PROCESSED

    - name: Transition change request to review with notes
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_sys_id }}"
        state: review
        other:
          work_notes: "{{ closing_notes }}"
      register: cr_review_result

    - name: Close change request with notes
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_sys_id }}"
        state: closed
        close_code: successful
        close_notes: "{{ closing_notes }}"
        other:
          work_notes: "{{ closing_notes }}"
      register: cr_close_result

    - name: Extract related incident identifiers from change request text
      ansible.builtin.set_fact:
        incident_sys_id: "{{ incident_sys_id | default(description | default('') | regex_search('Incident Sys ID:\\s*([0-9a-f]{32})', '\\1')) }}"
        incident_number: "{{ incident_number | default(short_description | default('') | regex_search('INC[0-9]+')) | default(description | default('') | regex_search('INC[0-9]+')) }}"

    - name: Update related incident with closing notes (by sys_id if available)
      servicenow.itsm.incident:
        sys_id: "{{ incident_sys_id }}"
        state: closed
        close_code: successful
        close_notes: "{{ closing_notes }}"
        other:
          comments: "{{ closing_notes }}"
      when: (incident_sys_id | default('')) | length > 0
      register: incident_close_result_by_id

    - name: Update related incident with closing notes (by number if sys_id missing)
      servicenow.itsm.incident:
        number: "{{ incident_number }}"
        state: closed
        close_code: successful
        close_notes: "{{ closing_notes }}"
        other:
          comments: "{{ closing_notes }}"
      when: ((incident_sys_id | default('')) | length == 0) and ((incident_number | default('')) | length > 0)
      register: incident_close_result_by_number

    - name: Show update result
      ansible.builtin.debug:
        msg: |
          Change Request {{ change_request_sys_id }} closed.
          Incident identifiers found - sys_id: {{ incident_sys_id | default('') }}, number: {{ incident_number | default('') }}
          Incident updated: {{ (incident_close_result_by_id is defined) or (incident_close_result_by_number is defined) }}

