---
- name: Create Software Change Request from ServiceNow Incident
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "{{ servicenow_instance | default('your-instance.service-now.com') }}"
    servicenow_username: "{{ servicenow_username | default('admin') }}"
    servicenow_password: "{{ servicenow_password | default('password') }}"
    
  tasks:
    - name: Debug received event data
      debug:
        msg: |
          Received ServiceNow incident data:
          - Incident Number: {{ incident_number }}
          - Incident Sys ID: {{ incident_sys_id }}
          - Category: {{ incident_category }}
          - Change Type: {{ change_type }}
          - Change Reason: {{ change_reason }}

    - name: Get incident details from ServiceNow
      servicenow.itsm.incident_info:
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        sys_id: "{{ incident_sys_id }}"
      register: incident_details

    - name: Debug incident details
      debug:
        msg: |
          Incident Details:
          - Short Description: {{ incident_details.incident.short_description }}
          - Description: {{ incident_details.incident.description }}
          - Priority: {{ incident_details.incident.priority }}
          - Urgency: {{ incident_details.incident.urgency }}
          - Impact: {{ incident_details.incident.impact }}
          - Assignment Group: {{ incident_details.incident.assignment_group }}
          - Assigned To: {{ incident_details.incident.assigned_to }}

    - name: Create change request in ServiceNow
      servicenow.itsm.change_request:
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        state: new
        short_description: "{{ change_reason }} - Related to Incident {{ incident_number }}"
        description: |
          This change request was automatically created based on ServiceNow incident {{ incident_number }}.
          
          Incident Details:
          - Incident Number: {{ incident_number }}
          - Incident Sys ID: {{ incident_sys_id }}
          - Incident Category: {{ incident_category }}
          - Incident Short Description: {{ incident_details.incident.short_description }}
          - Incident Description: {{ incident_details.incident.description }}
          - Incident Priority: {{ incident_details.incident.priority }}
          - Incident Urgency: {{ incident_details.incident.urgency }}
          - Incident Impact: {{ incident_details.incident.impact }}
          
          Change Request Details:
          - Change Type: {{ change_type }}
          - Reason: {{ change_reason }}
          
          This change request was automatically generated by Event-Driven Ansible based on incident analysis.
        category: "{{ incident_category }}"
        priority: "{{ incident_details.incident.priority }}"
        urgency: "{{ incident_details.incident.urgency }}"
        impact: "{{ incident_details.incident.impact }}"
        assignment_group: "{{ incident_details.incident.assignment_group }}"
        assigned_to: "{{ incident_details.incident.assigned_to }}"
        change_type: "{{ change_type }}"
        risk: medium
        implementation_plan: |
          Implementation Plan for Change Request related to Incident {{ incident_number }}:
          
          1. Review incident details and root cause analysis
          2. Assess impact and risk of proposed changes
          3. Develop detailed implementation steps
          4. Schedule change window during maintenance hours
          5. Execute change with proper testing
          6. Validate change resolution
          7. Close change request and update incident
        test_plan: |
          Test Plan for Change Request related to Incident {{ incident_number }}:
          
          1. Pre-change testing to establish baseline
          2. Test change in non-production environment
          3. Validate all functionality works as expected
          4. Perform rollback testing if applicable
          5. Post-change validation in production
        backout_plan: |
          Backout Plan for Change Request related to Incident {{ incident_number }}:
          
          1. Document current system state before change
          2. Prepare rollback procedures
          3. Test rollback process in non-production
          4. Ensure rollback can be executed within acceptable timeframe
          5. Have rollback team on standby during implementation
      register: change_request_result

    - name: Debug change request creation result
      debug:
        msg: |
          Change Request Created Successfully:
          - Change Request Number: {{ change_request_result.change_request.number }}
          - Change Request Sys ID: {{ change_request_result.change_request.sys_id }}
          - State: {{ change_request_result.change_request.state }}
          - Short Description: {{ change_request_result.change_request.short_description }}

    - name: Link change request to original incident
      servicenow.itsm.incident:
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        sys_id: "{{ incident_sys_id }}"
        work_notes: |
          Change Request Created: {{ change_request_result.change_request.number }}
          Change Request Sys ID: {{ change_request_result.change_request.sys_id }}
          
          This incident has been linked to a change request for resolution.
          Please refer to the change request for implementation details and progress updates.
      when: change_request_result is defined and change_request_result.change_request is defined

    - name: Post change request creation event to EDA
      ansible.builtin.uri:
        url: "{{ eda_webhook_url | default('http://localhost:5000/api/events') }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          event_type: "change_request_created"
          source: "servicenow_incident_monitor"
          data:
            incident_number: "{{ incident_number }}"
            incident_sys_id: "{{ incident_sys_id }}"
            change_request_number: "{{ change_request_result.change_request.number }}"
            change_request_sys_id: "{{ change_request_result.change_request.sys_id }}"
            change_type: "{{ change_type }}"
            change_reason: "{{ change_reason }}"
            created_at: "{{ ansible_date_time.iso8601 }}"
        status_code: [200, 201, 202]
      when: eda_webhook_url is defined
      ignore_errors: true

    - name: Set fact for change request details
      set_fact:
        change_request_created: true
        change_request_number: "{{ change_request_result.change_request.number }}"
        change_request_sys_id: "{{ change_request_result.change_request.sys_id }}"

    - name: Display success message
      debug:
        msg: |
          ✅ Change Request Successfully Created!
          
          Change Request Details:
          - Number: {{ change_request_result.change_request.number }}
          - Sys ID: {{ change_request_result.change_request.sys_id }}
          - Related Incident: {{ incident_number }}
          - Change Type: {{ change_type }}
          - Reason: {{ change_reason }}
          
          The change request has been linked to the original incident and is ready for review and approval.
