---
- name: Create Software Change Request from ServiceNow Incident
  hosts: localhost
  gather_facts: false
  vars:
    # Extract variables from the event data structure
    incident_number: "{{ ansible_eda.event.number }}"
    incident_sys_id: "{{ ansible_eda.event.sys_id }}"
    incident_category: "{{ ansible_eda.event.category }}"
    incident_short_description: "{{ ansible_eda.event.short_description }}"
    incident_description: "{{ ansible_eda.event.description }}"
    incident_priority: "{{ ansible_eda.event.priority }}"
    incident_urgency: "{{ ansible_eda.event.urgency }}"
    incident_impact: "{{ ansible_eda.event.impact }}"
    incident_assignment_group: "{{ ansible_eda.event.assignment_group }}"
    incident_assigned_to: "{{ ansible_eda.event.assigned_to }}"
    # Set default values for change request fields if not provided
    change_type: "{{ ansible_eda.event.change_type | default('standard') }}"
    change_reason: "{{ ansible_eda.event.change_reason | default('Automated change request based on incident analysis') }}"
  tasks:
    - name: Debug received event data
      debug:
        msg: |
          Received ServiceNow incident data:
          - Incident Number: {{ incident_number }}
          - Incident Sys ID: {{ incident_sys_id }}
          - Category: {{ incident_category }}
          - Change Type: {{ change_type }}
          - Change Reason: {{ change_reason }}

    - name: Get incident details from ServiceNow
      servicenow.itsm.incident_info:
        sys_id: "{{ incident_sys_id }}"
      register: incident_details

    - name: Debug incident details
      debug:
        msg: |
          Incident Details:
          - Short Description: {{ incident_short_description }}
          - Description: {{ incident_description }}
          - Priority: {{ incident_priority }}
          - Urgency: {{ incident_urgency }}
          - Impact: {{ incident_impact }}
          - Assignment Group: {{ incident_assignment_group }}
          - Assigned To: {{ incident_assigned_to }}

    - name: Check for existing change requests linked to incident
      servicenow.itsm.change_request_info:
        sysparm_query: "descriptionLIKE{{ incident_number }}"
      register: existing_change_requests

    - name: Debug existing change requests
      debug:
        msg: |
          Existing Change Requests Found: {{ existing_change_requests.records | length }}
          {% for cr in existing_change_requests.records %}
          - Change Request: {{ cr.number }} ({{ cr.sys_id }}) - State: {{ cr.state }}
          {% endfor %}

    - name: Create change request in ServiceNow
      servicenow.itsm.change_request:
        state: new
        short_description: "{{ change_reason }} - Related to Incident {{ incident_number }}"
        description: |
          This change request was automatically created based on ServiceNow incident {{ incident_number }}.

          Incident Details:
          - Incident Number: {{ incident_number }}
          - Incident Sys ID: {{ incident_sys_id }}
          - Incident Category: {{ incident_category }}
          - Incident Short Description: {{ incident_short_description }}
          - Incident Description: {{ incident_description }}
          - Incident Priority: {{ incident_priority }}
          - Incident Urgency: {{ incident_urgency }}
          - Incident Impact: {{ incident_impact }}

          Change Request Details:
          - Change Type: {{ change_type }}
          - Reason: {{ change_reason }}

          This change request was automatically generated by Event-Driven Ansible based on incident analysis.
        category: "{{ incident_category }}"
        priority: "{{ incident_priority }}"
        urgency: "{{ incident_urgency }}"
        impact: "{{ incident_impact }}"
        assignment_group: "{{ incident_assignment_group }}"
        risk: medium
        type: "{{ change_type }}"
      register: change_request_result
      when: existing_change_requests.records | length == 0

    - name: Debug change request creation result
      debug:
        msg: |
          Change Request Created Successfully:
          - Change Request Number: {{ change_request_result.record.number }}
          - Change Request Sys ID: {{ change_request_result.record.sys_id }}
          - State: {{ change_request_result.record.state }}
          - Short Description: {{ change_request_result.record.short_description }}
      when: change_request_result is defined and change_request_result.record is defined

    - name: Link change request to original incident
      servicenow.itsm.incident:
        sys_id: "{{ incident_sys_id }}"
        description: |
          This incident has been linked to change request {{ change_request_result.record.number }} for resolution.

          Change Request Details:
          - Number: {{ change_request_result.record.number }}
          - Sys ID: {{ change_request_result.record.sys_id }}
          - State: {{ change_request_result.record.state }}

          Please refer to the change request for implementation details and progress updates.
      when: change_request_result is defined and change_request_result.record is defined

    - name: Set fact for change request details
      set_fact:
        change_request_created: true
        change_request_number: "{{ change_request_result.record.number }}"
        change_request_sys_id: "{{ change_request_result.record.sys_id }}"
      when: change_request_result is defined and change_request_result.record is defined

    - name: Display success message for new change request
      debug:
        msg: |
          Change Request Successfully Created!

          Change Request Details:
          - Number: {{ change_request_result.record.number }}
          - Sys ID: {{ change_request_result.record.sys_id }}
          - Related Incident: {{ incident_number }}
          - Change Type: {{ change_type }}
          - Reason: {{ change_reason }}

          The change request has been linked to the original incident and is ready for review and approval.
      when: change_request_result is defined and change_request_result.record is defined

    - name: Display message when change request already exists
      debug:
        msg: |
          Skipping Change Request Creation - Incident Already Has Linked Change Request(s)

          Existing Change Request(s):
          {% for cr in existing_change_requests.records %}
          - Change Request: {{ cr.number }} ({{ cr.sys_id }}) - State: {{ cr.state }}
          {% endfor %}

          Incident {{ incident_number }} already has {{ existing_change_requests.records | length }} linked change request(s). No new change request will be created.
      when: existing_change_requests.records | length > 0
