---
- name: Create Test Change Request in ServiceNow
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "https://dev347897.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "Xa$2bgxP$NO5"

  tasks:
    - name: Create test change request
      servicenow.itsm.change_request:
        state: new
        short_description: "Test Change Request for EDA Activation"
        description: "This is a test change request created to verify EDA activation is working correctly. It should trigger the scheduled change request processing rule."
        priority: "3"
        urgency: "3"
        impact: "3"
        type: "standard"
        risk: "medium"
        assignment_group: "IT Operations"
        assigned_to: "admin"
        planned_start_date: "{{ ansible_date_time.iso8601 }}"
        planned_end_date: "{{ (ansible_date_time.epoch | int + 3600) | strftime('%Y-%m-%d %H:%M:%S') }}"
        work_notes: "Test change request created by Ansible for EDA testing"
      register: change_request_result

    - name: Display created change request details
      debug:
        msg: |
          Test Change Request Created Successfully!
          
          Change Request Details:
          - Number: {{ change_request_result.record.number }}
          - Sys ID: {{ change_request_result.record.sys_id }}
          - Short Description: {{ change_request_result.record.short_description }}
          - State: {{ change_request_result.record.state }}
          - Priority: {{ change_request_result.record.priority }}
          - Planned Start Date: {{ change_request_result.record.planned_start_date }}
          - Planned End Date: {{ change_request_result.record.planned_end_date }}
          - Assignment Group: {{ change_request_result.record.assignment_group }}
          - Assigned To: {{ change_request_result.record.assigned_to }}

    - name: Update change request to scheduled state
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_result.record.sys_id }}"
        state: scheduled
        work_notes: |
          Change request moved to scheduled state for EDA testing.
          
          This change request should now trigger the EDA activation:
          - State: scheduled ✓
          - Planned Start Date: defined ✓
          
          EDA should process this change request and move it to implementation state.
      register: scheduled_result

    - name: Display scheduled change request details
      debug:
        msg: |
          Change Request Successfully Scheduled!
          
          Final Change Request Details:
          - Number: {{ scheduled_result.record.number }}
          - Sys ID: {{ scheduled_result.record.sys_id }}
          - State: {{ scheduled_result.record.state }}
          - Planned Start Date: {{ scheduled_result.record.planned_start_date }}
          - Planned End Date: {{ scheduled_result.record.planned_end_date }}
          
          The EDA activation should now detect this change request and process it.
          Check the EDA activation logs to see if it fires!

    - name: Set fact for change request info
      set_fact:
        test_change_request_number: "{{ scheduled_result.record.number }}"
        test_change_request_sys_id: "{{ scheduled_result.record.sys_id }}"
        test_change_request_state: "{{ scheduled_result.record.state }}"
