---
- name: Query ServiceNow for Change Requests
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "https://dev347897.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "Xa$2bgxP$NO5"

  tasks:
    - name: Query all change requests
      servicenow.itsm.change_request_info:
        query:
          - state: "scheduled"
        fields:
          - sys_id
          - number
          - short_description
          - state
          - priority
          - urgency
          - impact
          - planned_start_date
          - planned_end_date
          - assignment_group
          - assigned_to
          - sys_created_on
          - sys_updated_on
      register: change_requests

    - name: Display found change requests
      debug:
        msg: |
          Found {{ change_requests.records | length }} change requests in scheduled state:
          {% for cr in change_requests.records %}
          - Number: {{ cr.number }}
            Sys ID: {{ cr.sys_id }}
            Short Description: {{ cr.short_description }}
            State: {{ cr.state }}
            Priority: {{ cr.priority }}
            Planned Start: {{ cr.planned_start_date }}
            Planned End: {{ cr.planned_end_date }}
            Assignment Group: {{ cr.assignment_group }}
            Assigned To: {{ cr.assigned_to }}
            Created: {{ cr.sys_created_on }}
            Updated: {{ cr.sys_updated_on }}
          {% endfor %}

    - name: Query all change requests (any state)
      servicenow.itsm.change_request_info:
        query:
          - state: "!=closed"
        fields:
          - sys_id
          - number
          - short_description
          - state
          - priority
          - planned_start_date
      register: all_change_requests

    - name: Display all change requests
      debug:
        msg: |
          Found {{ all_change_requests.records | length }} change requests (any state):
          {% for cr in all_change_requests.records %}
          - Number: {{ cr.number }}
            Sys ID: {{ cr.sys_id }}
            Short Description: {{ cr.short_description }}
            State: {{ cr.state }}
            Priority: {{ cr.priority }}
            Planned Start: {{ cr.planned_start_date }}
          {% endfor %}
