---
- name: "SNOW: Reinstall Agent - Nagios NCPA Agent for RHEL 8/9"
  hosts: "{{ hostname | default('all') }}"
  gather_facts: true
  become: true
  module_defaults:
    ansible.builtin.dnf:
      use_backend: dnf4

  vars:
    nagios_repo_url: "https://repo.nagios.com/nagios/9/nagios-repo-9-2.el9.noarch.rpm"
    ncpa_package: "ncpa"
    ncpa_service_name: "ncpa"
    ncpa_config_file: "/usr/local/ncpa/etc/ncpa.cfg"
    ncpa_port: 5693
    ncpa_api_token: "{{ nagios_api_token | default('K9pL3mX7vR2tQ8nJ') }}"

  tasks:
    - name: Check if NCPA is already installed and running
      ansible.builtin.systemd:
        name: "{{ ncpa_service_name }}"
      register: ncpa_service_status
      failed_when: false

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if NCPA package is installed
      ansible.builtin.set_fact:
        ncpa_installed: "{{ ncpa_package in ansible_facts.packages }}"

    - name: Check if Nagios repository is already installed
      ansible.builtin.shell: rpm -q nagios-repo
      register: nagios_repo_status
      failed_when: false
      changed_when: false

    - name: Set fact for Nagios repository installation status
      ansible.builtin.set_fact:
        nagios_repo_installed: "{{ nagios_repo_status.rc == 0 }}"

    - name: Install Nagios repository for RHEL 8/9
      ansible.builtin.get_url:
        url: "{{ nagios_repo_url }}"
        dest: "/tmp/nagios-repo.rpm"
      when: not ncpa_installed and not nagios_repo_installed

    - name: Install Nagios repository RPM
      ansible.builtin.shell: rpm -i /tmp/nagios-repo.rpm
      when: not ncpa_installed and not nagios_repo_installed
      failed_when: false

    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true
      when: not ncpa_installed

    - name: Clean package cache
      ansible.builtin.dnf:
        clean: all
      when: not ncpa_installed

    - name: Install NCPA agent
      ansible.builtin.dnf:
        name: "{{ ncpa_package }}"
        state: present
      register: ncpa_install_result
      when: not ncpa_installed

    - name: Verify NCPA installation
      ansible.builtin.package_facts:
        manager: auto
      register: ncpa_verify_result

    - name: Configure NCPA API token
      ansible.builtin.lineinfile:
        path: "{{ ncpa_config_file }}"
        regexp: '^community_string = '
        line: 'community_string = {{ ncpa_api_token }}'
        backup: true
      notify: restart ncpa

    - name: Start and enable NCPA service
      ansible.builtin.systemd:
        name: "{{ ncpa_service_name }}"
        state: started
        enabled: true
        daemon_reload: true

    - name: Check if firewalld is active
      ansible.builtin.systemd:
        name: firewalld
      register: firewalld_status
      failed_when: false

    - name: Configure firewall for NCPA port
      ansible.builtin.shell: |
        firewall-cmd --permanent --add-port={{ ncpa_port }}/tcp
        firewall-cmd --reload
      when: firewalld_status.status.ActiveState == "active"
      failed_when: false

    - name: Verify NCPA service is running
      ansible.builtin.systemd:
        name: "{{ ncpa_service_name }}"
      register: ncpa_final_status

    - name: Test NCPA web interface accessibility
      ansible.builtin.uri:
        url: "https://{{ ansible_default_ipv4.address }}:{{ ncpa_port }}/"
        method: GET
        validate_certs: false
        timeout: 10
      register: ncpa_web_test
      failed_when: false

    - name: Display installation status
      ansible.builtin.debug:
        msg: |
          Nagios NCPA agent installation completed:
          - Package installed: {{ ncpa_package in ansible_facts.packages }}
          - Service status: {{ ncpa_final_status.status.ActiveState }}
          - Service enabled: {{ ncpa_final_status.status.UnitFileState }}
          - Web interface accessible: {{ ncpa_web_test.status == 200 if ncpa_web_test.status is defined else 'Unknown' }}
          - Configuration file: {{ ncpa_config_file }}
          - API Token: {{ ncpa_api_token }}
          - Access URL: https://{{ ansible_default_ipv4.address }}:{{ ncpa_port }}/

  handlers:
    - name: restart ncpa
      ansible.builtin.systemd:
        name: "{{ ncpa_service_name }}"
        state: restarted
        daemon_reload: true
