---
- name: Track Change Request Implementation Progress
  hosts: localhost
  gather_facts: false
  vars:
    # Extract variables from the event data structure
    change_request_number: "{{ ansible_eda.event.change_request_number }}"
    change_request_sys_id: "{{ ansible_eda.event.change_request_sys_id }}"
    change_request_state: "{{ ansible_eda.event.change_request_state }}"
    start_date: "{{ ansible_eda.event.start_date }}"
    planned_end_date: "{{ ansible_eda.event.planned_end_date }}"
    assignment_group: "{{ ansible_eda.event.assignment_group }}"
    assigned_to: "{{ ansible_eda.event.assigned_to }}"
    work_notes: "{{ ansible_eda.event.work_notes }}"
    implementation_notes: "{{ ansible_eda.event.implementation_notes }}"

  tasks:
    - name: Debug received implementation tracking data
      debug:
        msg: |
          Received ServiceNow change request implementation tracking data:
          - Change Request Number: {{ change_request_number }}
          - Change Request Sys ID: {{ change_request_sys_id }}
          - State: {{ change_request_state }}
          - Start Date: {{ start_date }}
          - Planned End Date: {{ planned_end_date }}
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}
          - Work Notes: {{ work_notes }}
          - Implementation Notes: {{ implementation_notes }}

    - name: Get change request details from ServiceNow
      servicenow.itsm.change_request_info:
        sys_id: "{{ change_request_sys_id }}"
      register: change_request_details

    - name: Calculate implementation progress
      set_fact:
        current_time: "{{ ansible_date_time.epoch | int }}"
        start_time: "{{ start_date | to_datetime('%Y-%m-%d %H:%M:%S') | int }}"
        end_time: "{{ planned_end_date | to_datetime('%Y-%m-%d %H:%M:%S') | int }}"
        total_duration: "{{ (end_time - start_time) | int }}"
        elapsed_time: "{{ (current_time - start_time) | int }}"
        progress_percentage: "{{ ((elapsed_time / total_duration) * 100) | round(2) }}"

    - name: Debug progress calculation
      debug:
        msg: |
          Implementation Progress Calculation:
          - Current Time: {{ current_time }}
          - Start Time: {{ start_time }}
          - End Time: {{ end_time }}
          - Total Duration: {{ total_duration }} seconds
          - Elapsed Time: {{ elapsed_time }} seconds
          - Progress Percentage: {{ progress_percentage }}%

    - name: Update change request with progress tracking
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_sys_id }}"
        work_notes: |
          {{ work_notes }}
          
          Implementation Progress Update:
          - Current State: {{ change_request_state }}
          - Implementation Start: {{ start_date }}
          - Planned End: {{ planned_end_date }}
          - Progress: {{ progress_percentage }}% complete
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}
          
          {% if implementation_notes is defined and implementation_notes != "" %}
          Implementation Notes: {{ implementation_notes }}
          {% endif %}
          
          Progress tracked by Event-Driven Ansible at {{ ansible_date_time.iso8601 }}.
      register: change_request_progress_result

    - name: Debug progress update result
      debug:
        msg: |
          Change Request Progress Updated:
          - Change Request Number: {{ change_request_progress_result.record.number }}
          - Progress Percentage: {{ progress_percentage }}%
          - Work Notes Updated: Yes
          - Update Time: {{ ansible_date_time.iso8601 }}

    - name: Check if change request is approaching deadline
      set_fact:
        time_remaining: "{{ (end_time - current_time) | int }}"
        hours_remaining: "{{ (time_remaining / 3600) | round(2) }}"
        is_approaching_deadline: "{{ time_remaining < 3600 }}"

    - name: Alert if approaching deadline
      servicenow.itsm.change_request:
        sys_id: "{{ change_request_sys_id }}"
        work_notes: |
          {{ work_notes }}
          
          ⚠️ DEADLINE ALERT ⚠️
          - Change request is approaching its planned end date
          - Time remaining: {{ hours_remaining }} hours
          - Planned end date: {{ planned_end_date }}
          - Current progress: {{ progress_percentage }}%
          
          Please ensure implementation is completed on time or request an extension.
          
          Alert generated by Event-Driven Ansible at {{ ansible_date_time.iso8601 }}.
      when: is_approaching_deadline

    - name: Set fact for progress tracking
      set_fact:
        change_request_tracked: true
        change_request_number: "{{ change_request_number }}"
        change_request_sys_id: "{{ change_request_sys_id }}"
        progress_percentage: "{{ progress_percentage }}"
        hours_remaining: "{{ hours_remaining }}"
        is_approaching_deadline: "{{ is_approaching_deadline }}"

    - name: Display progress tracking success message
      debug:
        msg: |
          Change Request Implementation Progress Tracked!

          Change Request Details:
          - Number: {{ change_request_number }}
          - Sys ID: {{ change_request_sys_id }}
          - State: {{ change_request_state }}
          - Progress: {{ progress_percentage }}% complete
          - Hours Remaining: {{ hours_remaining }}
          - Approaching Deadline: {{ is_approaching_deadline }}
          - Assignment Group: {{ assignment_group }}
          - Assigned To: {{ assigned_to }}

          Implementation progress has been tracked and updated in ServiceNow.
